import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { fileURLToPath } from "node:url";
import { PNG } from "pngjs";
import { imageSurfaceSites, imageSpawnGroups, opaqueRectangles } from "../shared/image-terrain.js";

const directory = new URL("../public/maps/", import.meta.url);
const metadata = JSON.parse(readFileSync(new URL("catalog.json", directory), "utf8"));
const maps = readdirSync(directory).filter((name) => name.endsWith(".png")).sort().map((file) => {
  const id = file.slice(0, -4);
  const bytes = readFileSync(new URL(file, directory));
  const { width, height, data } = PNG.sync.read(bytes);
  if (width > 8192 || height > 4096) throw new Error(`${file}: maximum map size is 8192 × 4096`);
  const rectangles = opaqueRectangles(width, height, data);
  const info = metadata[id] ?? {};
  const hasWater = Number.isFinite(info.waterY);
  const waterY = hasWater ? info.waterY : height + 1000;
  const platforms = rectangles.map(([x, y, w, h], i) => ({ id: `${id}-${i}`, x, y, w, h }));
  const supplySites = imageSurfaceSites(width, height, data, platforms, 18, waterY);
  const mineSites = imageSurfaceSites(width, height, data, platforms, 8, waterY);
  const spawnGroups = imageSpawnGroups(supplySites);
  if (spawnGroups.length < 2) throw new Error(`${file}: needs two sheltered areas with room for six frogs each; curved ground and separate branches are supported`);
  const ordered = spawnGroups.map((group) => platforms.findIndex((p) =>
    p.y === group[0].y + 18 && group[0].x + 18 > p.x && group[0].x - 18 < p.x + p.w));
  console.log(`${file}: ${width} × ${height}, ${rectangles.length} exact solids, ${spawnGroups.length} team areas`);
  return { id, name: info.name ?? id.split("-").map((word) => word[0].toUpperCase() + word.slice(1)).join(" "),
    description: info.description ?? "An image arena. Every fully opaque pixel is solid terrain.",
    size: info.size ?? "Medium", theme: info.theme ?? "islands", terrain: info.terrain ?? "PNG terrain · Opaque pixels are solid",
    image: `/maps/${file}?v=${createHash("sha256").update(bytes).digest("hex").slice(0, 12)}`,
    width, height, waterY, hasWater, rectangles, spawns: ordered, spawnGroups, supplySites, mineSites };
});
const output = `// Generated by npm run maps:compile. Edit public/maps/*.png, not this file.\nimport type { ArenaMap } from "./maps.js";\nimport type { PixelRect } from "./image-terrain.js";\nexport const IMAGE_MAP_DATA: (Omit<ArenaMap, "platforms" | "spawnPlatformIds"> & { rectangles: PixelRect[]; spawns: number[] })[] = ${JSON.stringify(maps)};\n`;
const target = new URL("../shared/image-maps.generated.ts", import.meta.url);
let previous = "";
try { previous = readFileSync(target, "utf8"); } catch { /* first build */ }
if (previous !== output) writeFileSync(fileURLToPath(target), output);
